name: MEXC 1H Strategy Scanner

on:
  schedule:
    - cron: "0 * * * *"   # her saat başı (UTC)
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas numpy requests

      - name: Run scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:        ${{ secrets.CHAT_ID }}
          EXCHANGE: "mexc"
          TIMEFRAME: "1h"
          LIMIT: "300"
          EMA_FAST: "10"
          EMA_MID: "20"
          EMA_SLOW: "30"
          RSI_WINDOW: "14"
          RSI_MIN: "50"
          PRICE_MAX_CHANGE: "0.05"
          PRICE_MIN_CHANGE: "-0.02"
          CROSS_LOOKBACK: "2"
          STOP_LOSS_PCT: "0.03"
          SCAN_PAUSE: "0.15"
          CSV_OUT: "mexc_1h_strategy_hits.csv"
        run: |
          python main.py

      - name: Upload CSV artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mexc-1h-hits
          path: mexc_1h_strategy_hits.csv
          if-no-files-found: ignore
